name: Check Docs Build

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  check-docs:
    name: Check Docs Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          
      - name: Install dependencies
        run: npm install

      - name: Build VitePress docs
        run: npm run docs:build